name: Terraform Deployment

on:

  workflow_dispatch:

    inputs:

      deployment_id:

        required: true

        type: string

jobs:

  deploy:

    runs-on: ubuntu-latest

    defaults:

      run:

        working-directory: terraform/deployments/${{ github.event.inputs.deployment_id }}

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init

        run: terraform init

      - name: Terraform Validate

        run: terraform validate

      - name: Terraform Plan

        run: terraform plan

      - name: Terraform Apply

        run: terraform apply -auto-approve